### ISSUE TITLE
Fire plugin controls with speech interaction

### ISSUE THREAD

**Issue by ChristopherStephan** [ChristopherStephan/IWGI-Speech#15]
Hello Christopher ,

to invoke the drawing commands,  all you need to do is Just putting  the following code  into the onclick handler of your custom buttons (or wherever you want).

new L.Draw.Polygon(map, drawControl.options.polygon).enable()  // to invoke draw polygon command  

new L.Draw.Rectangle(map, drawControl.options.rectangle).enable() // to invoke draw Rectangle command  

new L.Draw.Circle(map, drawControl.options.circle).enable() // to invoke draw Circle command  

new L.Draw.Marker(map, drawControl.options.marker).enable( )// to invoke draw Marker command  

Regards

Ahmed

**Comment by ChristopherStephan** [comment]
Enabling the control with the code above works but then click events are bound to the current position of the mouse pointer. The mouse pointer cannot be manipulated programmatically with JS for safety reasons. See http://stackoverflow.com/questions/4752501/move-the-mouse-pointer-to-a-specific-position.

**Comment by ChristopherStephan** [comment]
Workaround for geometries: Large/Medium/Small <geometry> speech commands.

**Comment by schlomm** [comment]
I think, this issue is also fixed (somehow :-P).
Firstly the user has to navigate to the position, where the marker should be placed, and after that the commands should be fired to place the marker (by speech, gesture or click).
