### ISSUE TITLE
Dropdown Menu for different languages 

### ISSUE THREAD

**Issue by schlomm** [ChristopherStephan/IWGI-Speech#22]
Dropdown menu should offer the option to switch between several languages.

**Comment by ChristopherStephan** [comment]
Low priority. Would require a dictionary of commands in the specific language.

**Comment by ChristopherStephan** [comment]
A dropdown box only for different "english" varieties is a nice to have.

**Comment by ChristopherStephan** [comment]
Dropdown box should be placed in Speech/Layer sidebar.
