### ISSUE TITLE
List often incorrect understood voice phrases for each voice command and add each in the related command.

### ISSUE THREAD

**Issue by MojioMS** [ChristopherStephan/IWGI-Speech#24]
List often incorrect understood voice phrases for each voice command (e.g. 'white' to 'right' in panning) and add each in the related command:

Commands:

enable temperature map, disable temperature map

map action command (zoom in, zoom out, left, right, up, down)

point, large circle, medium circle, small circle, large rectangle, medium rectangle, small rectangle

show me where i am, end show me where i am

enable additional information, disable additional information

go back to home, start measurement, end measurement

minimize minimap, maximize minimap

start marker drawing, start line drawing, start circle drawing, start polygon drawing, start rectangle drawing

**Comment by MojioMS** [comment]
zoom in, zoom out work fine.
left: net, next
right: white, fight
up: apple
down works fine.

**Comment by schlomm** [comment]
We could control/use these commands with PocketSphinx. There we can define a dictonary/grammar file, which might end in better results. For continous text we should use the WebSpeech API.

**Comment by ChristopherStephan** [comment]
Idea discarded. Commands should be shortened.
