### ISSUE TITLE
Animations don't work.

### ISSUE THREAD

**Issue by schlomm** [ChristopherStephan/IWGI-Speech#7]
Animations for navigation operations don't work anymore. Problem occurred after using sidebar?!  Cf. history: https://github.com/ChristopherStephan/IWGI-Speech/commits/master/SpeechAndLeaflet/SpeechAndLeaflet.html 
Probably a .css error.

**Comment by ChristopherStephan** [comment]
Fixed CSS class of command_animation and the callback functions for resetting the values after each animation. Closes #7.
